SERIAL_DRIVER = vendor
BOOTLOADER = rp2040

CONSOLE_ENABLE = no
NKRO_ENABLE = no
SLEEP_LED_ENABLE = no
COMMAND_ENABLE = no

BACKLIGHT_ENABLE = no
LED_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
